name: ragenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asyncpg==0.30.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - distro==1.9.0
      - dnspython==2.8.0
      - email-validator==2.3.0
      - fastapi==0.120.4
      - filelock==3.20.0
      - fsspec==2025.10.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.2.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hyperframe==6.1.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-core==1.0.2
      - langchain-text-splitters==1.0.0
      - langsmith==0.4.39
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.6.1
      - orjson==3.11.4
      - packaging==25.0
      - pillow==12.0.0
      - portalocker==3.2.0
      - protobuf==6.33.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pypdf2==3.0.1
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - qdrant-client==1.15.1
      - redis==7.0.1
      - regex==2025.10.23
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - starlette==0.49.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.5.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - zstandard==0.25.0
prefix: /home/ankritrisal/miniconda3/envs/ragenv
